language: java

jdk:
  - openjdk11

os:
  - linux

services:
  - docker

branches:
  only:
    - master

before_install:
  - cd implementation/scipamato
  - chmod +x gradlew
  - chmod +x travis_script.sh

script:
  - travis_wait 40 ./travis_script.sh

cache:
  directories:
    - $HOME/.gradle
