language: java

jdk:
  - openjdk11

os:
  - linux

services:
  - docker

branches:
  only:
    - master

before_install:
  - cd implementation/scipamato
  - chmod +x gradlew

script:
  - travis_wait [ -n "${SONAR_TOKEN}" ] && ./gradlew sonarqube || ./gradlew check

cache:
  timeout: 1000
  directories:
    - $HOME/.gradle
